"""
make_locality_pgf.py -- generate the data for Fig. "repair share vs recovered ASR"
(paper/fig_locality_data.tex) straight from results/raw, so no number in the
figure is typed by hand.

Each point is one rolled-back shard subset: x = repair share covered (%),
y = ASR (%). Subsets containing both layer2 (shard 2) and layer4 (shard 4)
are drawn as a separate series.

Sources, in priority order:
  1. --s42 and --s0: both all-subsets JSONs (default, recommended)
     Defaults: results/raw/all_subsets/finetune_s42_bb_n6.json
               results/raw/all_subsets/finetune_s0_bb_n6.json
     Produces 63 + 63 = 126 points (all non-empty subsets x 2 seeds).
  2. --all-subsets: single all-subsets JSON (overrides --s42/--s0)
  3. --legacy: legacy pooled data from kshard* + substitution/n6 + share JSONs

Usage (run from repo root):
    python scripts/make_locality_pgf.py
    python scripts/make_locality_pgf.py \\
        --s42 results/raw/all_subsets/finetune_s42_bb_n6.json \\
        --s0  results/raw/all_subsets/finetune_s0_bb_n6.json
    python scripts/make_locality_pgf.py --legacy
"""
import argparse
import glob
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def legacy_points():
    share = {r["shard_idx"]: r["share_s"] for r in
             json.load(open(os.path.join(ROOT, "results/raw/share/share_n6.json")))["shards"]}
    pts = {}
    for f in glob.glob(os.path.join(ROOT, "results/raw/kshard*/kshard_curve_n6.json")):
        if "anp" in f:
            continue
        for v in json.load(open(f)).values():
            for name, r in v.get("strategies", {}).items():
                if name == "random":
                    for d, a, c in zip(r["draws"], r["asr_per_draw"], r["ca_per_draw"]):
                        pts[tuple(sorted(d))] = (a, c)
                else:
                    pts[tuple(sorted(r["shards"]))] = (r["asr"], r["ca"])
    for f in glob.glob(os.path.join(ROOT, "results/raw/substitution/n6/shard*.json")):
        j = json.load(open(f))
        pts[(j["shard_idx"],)] = (j["asr"], j["ca"])
    return [(sub, 100 * sum(share[s] for s in sub), a, c) for sub, (a, c) in pts.items() if sub]


def subset_points(path):
    """
    Load subset records from JSON.
    Handles two formats:
      - {"subsets": [{"shards": [...], "share_covered": float, "asr": float, "ca": float}, ...]}
      - [{"subset": [...], "k": int, "share_covered": float, "asr": float, "ca": float}, ...]
    Returns list of (shards_tuple, share_pct, asr, ca).
    """
    d = json.load(open(path))
    records = d["subsets"] if isinstance(d, dict) else d
    result = []
    for r in records:
        shards = r.get("shards") or r.get("subset", [])
        if not shards:
            continue
        result.append((
            tuple(sorted(shards)),
            100 * r["share_covered"],
            r["asr"],
            r["ca"],
        ))
    return result


def coords(points):
    return "\n".join(f"    ({x:.2f}, {y:.2f})  % {list(sub)} CA={ca:.2f}"
                     for sub, x, y, ca in sorted(points, key=lambda p: p[1]))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--legacy", action="store_true",
                    help="Use legacy pooled kshard + substitution/n6 JSONs instead of all-subsets")
    ap.add_argument("--s42",
                    default=os.path.join(ROOT, "results/raw/all_subsets/finetune_s42_bb_n6.json"),
                    help="Seed-42 all-subsets JSON (BackdoorBench normalization)")
    ap.add_argument("--s0",
                    default=os.path.join(ROOT, "results/raw/all_subsets/finetune_s0_bb_n6.json"),
                    help="Seed-0 all-subsets JSON (BackdoorBench normalization)")
    ap.add_argument("--all-subsets", default=None,
                    help="Single all-subsets JSON (overrides --s42/--s0 if given)")
    ap.add_argument("--anp", default=None,
                    help="ANP all-subsets JSON (optional, adds a third series)")
    ap.add_argument("--out",
                    default=os.path.join(ROOT, "paper/fig_locality_data.tex"))
    args = ap.parse_args()

    if args.legacy:
        pts = legacy_points()
        src = "legacy pooled kshard + substitution/n6 JSONs"
    elif args.all_subsets:
        pts = subset_points(args.all_subsets)
        src = args.all_subsets
    else:
        pts42 = subset_points(args.s42)
        pts0  = subset_points(args.s0)
        pts   = pts42 + pts0          # 63 + 63 = 126 non-empty subsets x 2 seeds
        src   = f"{args.s42} + {args.s0}"

    both = [p for p in pts if 2 in p[0] and 4 in p[0]]
    rest = [p for p in pts if not (2 in p[0] and 4 in p[0])]

    lines = [
        f"% AUTO-GENERATED by scripts/make_locality_pgf.py",
        f"% Sources: {src}",
        f"% Do not edit by hand -- rerun the script to update.",
        f"% {len(pts)} total points; {len(both)} contain shards 2 and 4.",
        f"% min ASR with {{2,4}}: {min(p[2] for p in both):.2f}; "
        f"max ASR without: {max(p[2] for p in rest):.2f}",
        "\\addplot[only marks, mark=o, mark size=2pt, color=blue!70!black] coordinates {",
        coords(rest), "};",
        "\\addlegendentry{Fine-tune, without \\{2,4\\}}",
        "\\addplot[only marks, mark=*, mark size=2pt, color=red!75!black] coordinates {",
        coords(both), "};",
        "\\addlegendentry{Fine-tune, with \\{2,4\\}}",
    ]
    if args.anp:
        anp_pts = subset_points(args.anp)
        lines += [
            "\\addplot[only marks, mark=triangle*, mark size=2.2pt, color=orange!85!black] coordinates {",
            coords(anp_pts), "};",
            "\\addlegendentry{ANP}",
        ]

    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {args.out}: {len(pts)} fine-tune points ({len(both)} with {{2,4}})"
          + (f", {len(subset_points(args.anp))} ANP points" if args.anp else ""))
    print(lines[3])
    print(lines[4])


if __name__ == "__main__":
    main()
