"""
make_kcurve_pgf.py -- generate Fig. fig:kcurve coordinate data from the
all-subsets JSONs, so no number in the figure is typed by hand.

fig:kcurve uses a dual y-axis tikzpicture:
  Left axis  (ASR %): paper/fig_kcurve_asr_data.tex  -- ASR seed-42, ASR seed-0
  Right axis (CA %):  paper/fig_kcurve_ca_data.tex   -- CA  seed-42, CA  seed-0

Both files are \input-ed by the tikzpicture in paper/main.tex.

Pattern follows make_locality_pgf.py per notes/2026-09-25_hung_supervisor.md.

Usage (run from repo root):
    python scripts/make_kcurve_pgf.py
    python scripts/make_kcurve_pgf.py \\
        --s42 results/raw/all_subsets/finetune_s42_bb_n6.json \\
        --s0  results/raw/all_subsets/finetune_s0_bb_n6.json \\
        --out-asr paper/fig_kcurve_asr_data.tex \\
        --out-ca  paper/fig_kcurve_ca_data.tex
"""
import argparse
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_records(path):
    """
    Load subset records from JSON.
    Handles two formats:
      - {"subsets": [{"shards": [...], ...}, ...]}   (s42 style)
      - [{"subset": [...], "k": int, ...}, ...]       (s0 style)
    Always returns records with a "shards" key.
    """
    d = json.load(open(path))
    records = d["subsets"] if isinstance(d, dict) else d
    normalized = []
    for r in records:
        if "shards" not in r:
            r = dict(r)
            r["shards"] = r.get("subset", [])
        normalized.append(r)
    return normalized


def load_index(path):
    """Return dict: frozenset(shards) -> (asr, ca) for every record in the JSON."""
    index = {}
    for r in load_records(path):
        key = frozenset(r["shards"])
        index[key] = (r["asr"], r["ca"])
    return index


def greedy_order(path):
    """
    Return shard indices sorted by share_covered descending (repair-aware order).
    Computed from the 1-shard records in path.
    """
    single = {}
    for r in load_records(path):
        if len(r["shards"]) == 1:
            single[r["shards"][0]] = r["share_covered"]
    return sorted(single, key=lambda s: single[s], reverse=True)


def coords_block(pairs):
    """pairs: list of (x, y); returns indented coordinate lines."""
    return "\n".join(f"    ({x}, {y:.2f})" for x, y in pairs)


def main():
    ap = argparse.ArgumentParser(
        description="Emit fig_kcurve_asr_data.tex and fig_kcurve_ca_data.tex "
                    "from all-subsets JSONs."
    )
    ap.add_argument(
        "--s42",
        default=os.path.join(ROOT, "results/raw/all_subsets/finetune_s42_bb_n6.json"),
        help="Seed-42 all-subsets JSON",
    )
    ap.add_argument(
        "--s0",
        default=os.path.join(ROOT, "results/raw/all_subsets/finetune_s0_bb_n6.json"),
        help="Seed-0 all-subsets JSON",
    )
    ap.add_argument(
        "--out-asr",
        default=os.path.join(ROOT, "paper/fig_kcurve_asr_data.tex"),
        help="Output .tex for ASR series (left axis, default: paper/fig_kcurve_asr_data.tex)",
    )
    ap.add_argument(
        "--out-ca",
        default=os.path.join(ROOT, "paper/fig_kcurve_ca_data.tex"),
        help="Output .tex for CA series (right axis, default: paper/fig_kcurve_ca_data.tex)",
    )
    args = ap.parse_args()

    idx42 = load_index(args.s42)
    idx0  = load_index(args.s0)

    # Greedy order from s42 (share_covered is geometry, same in both JSONs)
    order = greedy_order(args.s42)
    n_shards = len(order)  # 6

    # Build greedy path: k=0 (empty) .. k=6 (all shards)
    asr42, ca42, asr0, ca0 = [], [], [], []
    for k in range(n_shards + 1):
        subset = frozenset(order[:k])
        if subset not in idx42:
            raise KeyError(f"k={k} greedy subset {set(subset)} not found in s42 JSON")
        if subset not in idx0:
            raise KeyError(f"k={k} greedy subset {set(subset)} not found in s0 JSON")
        a42, c42 = idx42[subset]
        a0,  c0  = idx0[subset]
        asr42.append((k, a42))
        ca42.append((k, c42))
        asr0.append((k, a0))
        ca0.append((k, c0))

    # Annotate each k with the subset for the comment header
    path_rows = []
    for k in range(n_shards + 1):
        subset = set(order[:k])
        a42, c42 = idx42[frozenset(order[:k])]
        a0,  c0  = idx0[frozenset(order[:k])]
        path_rows.append(
            f"%   k={k}: shards={sorted(subset)}  "
            f"s42 ASR={a42:.2f} CA={c42:.2f}  s0 ASR={a0:.2f} CA={c0:.2f}"
        )

    header_common = [
        f"% Sources:",
        f"%   s42: {args.s42}",
        f"%   s0:  {args.s0}",
        f"% Greedy order (descending share_s): {order}",
        "% Greedy path:",
        *path_rows,
        "% Do not edit by hand -- rerun the script to update.",
        "",
    ]

    # ------------------------------------------------------------------
    # ASR file (left axis): ASR seed-42 and ASR seed-0
    # ------------------------------------------------------------------
    asr_lines = [
        "% AUTO-GENERATED by scripts/make_kcurve_pgf.py",
        *header_common,
        "% Series 1: ASR seed-42, greedy repair-aware path (red solid line)",
        r"\addplot[color=red!80!black, mark=*, mark size=2.5pt] coordinates {",
        coords_block(asr42),
        "};",
        r"\addlegendentry{ASR seed~42}",
        "",
        "% Series 2: ASR seed-0, greedy repair-aware path (orange dashed line)",
        r"\addplot[color=orange!80!black, mark=triangle*, mark size=2.5pt, dashed] coordinates {",
        coords_block(asr0),
        "};",
        r"\addlegendentry{ASR seed~0}",
    ]

    # ------------------------------------------------------------------
    # CA file (right axis): CA seed-42 and CA seed-0
    # ------------------------------------------------------------------
    ca_lines = [
        "% AUTO-GENERATED by scripts/make_kcurve_pgf.py",
        *header_common,
        "% Series 1: CA seed-42, greedy repair-aware path (blue dotted line)",
        r"\addplot[color=blue!70!black, mark=square*, mark size=2.5pt, dotted] coordinates {",
        coords_block(ca42),
        "};",
        r"\addlegendentry{CA seed~42}",
        "",
        "% Series 2: CA seed-0, greedy repair-aware path (teal dotted line)",
        r"\addplot[color=teal!70!black, mark=square, mark size=2.5pt, dotted] coordinates {",
        coords_block(ca0),
        "};",
        r"\addlegendentry{CA seed~0}",
    ]

    out_asr = vars(args)["out_asr"]
    out_ca  = vars(args)["out_ca"]

    os.makedirs(os.path.dirname(os.path.abspath(out_asr)), exist_ok=True)
    with open(out_asr, "w") as f:
        f.write("\n".join(asr_lines) + "\n")

    os.makedirs(os.path.dirname(os.path.abspath(out_ca)), exist_ok=True)
    with open(out_ca, "w") as f:
        f.write("\n".join(ca_lines) + "\n")

    print(f"Wrote {out_asr}  (ASR series, k=0..{n_shards})")
    print(f"Wrote {out_ca}  (CA series, k=0..{n_shards})")
    print(f"  Greedy order (repair-aware): {order}")
    print(f"  k  | ASR-s42  ASR-s0 | CA-s42  CA-s0")
    for k in range(n_shards + 1):
        a42, c42 = idx42[frozenset(order[:k])]
        a0,  c0  = idx0[frozenset(order[:k])]
        print(f"  {k}  | {a42:7.2f}  {a0:6.2f} | {c42:6.2f}  {c0:5.2f}")


if __name__ == "__main__":
    main()
