"""
make_singleshard_pgf.py -- generate Fig. fig:singleshard coordinate data
(paper/fig_singleshard_data.tex) from the all-subsets JSONs, so no number
in the figure is typed by hand.

Three \addplot coordinate blocks are emitted (no axis environment):
  1. share_s x 100  -- repair share per shard (blue bars)
  2. Single-shard ASR, seed-42 (red bars)
  3. Single-shard ASR, seed-0  (orange bars)

The output is \input-ed by the tikzpicture in paper/main.tex.

Pattern follows make_locality_pgf.py per notes/2026-09-25_hung_supervisor.md.

Usage (run from repo root):
    python scripts/make_singleshard_pgf.py
    python scripts/make_singleshard_pgf.py \
        --s42 results/raw/all_subsets/finetune_s42_bb_n6.json \
        --s0  results/raw/all_subsets/finetune_s0_bb_n6.json \
        --out paper/fig_singleshard_data.tex
"""
import argparse
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def single_shard_data(path):
    """Return dict: shard_idx -> (share_covered, asr, ca) for all 1-shard subsets."""
    d = json.load(open(path))
    result = {}
    for r in d["subsets"]:
        if len(r["shards"]) == 1:
            s = r["shards"][0]
            result[s] = (r["share_covered"], r["asr"], r["ca"])
    return result


def coords_block(pairs):
    """pairs: list of (x, y); returns indented coordinate lines."""
    return "\n".join(f"    ({x}, {y:.2f})" for x, y in pairs)


def main():
    ap = argparse.ArgumentParser(
        description="Emit fig_singleshard_data.tex from all-subsets JSONs."
    )
    ap.add_argument(
        "--s42",
        default=os.path.join(ROOT, "results/raw/all_subsets/finetune_s42_bb_n6.json"),
        help="Seed-42 all-subsets JSON",
    )
    ap.add_argument(
        "--s0",
        default=os.path.join(ROOT, "results/raw/all_subsets/finetune_s0_bb_n6.json"),
        help="Seed-0 all-subsets JSON",
    )
    ap.add_argument(
        "--out",
        default=os.path.join(ROOT, "paper/fig_singleshard_data.tex"),
        help="Output .tex file (default: paper/fig_singleshard_data.tex)",
    )
    args = ap.parse_args()

    data42 = single_shard_data(args.s42)
    data0  = single_shard_data(args.s0)

    n_shards = 6
    shards = list(range(n_shards))

    missing42 = [s for s in shards if s not in data42]
    missing0  = [s for s in shards if s not in data0]
    if missing42:
        raise ValueError(f"Missing single-shard records in s42 JSON for shards: {missing42}")
    if missing0:
        raise ValueError(f"Missing single-shard records in s0 JSON for shards: {missing0}")

    # share_s x 100: share_covered is geometry of the repair, same for both seeds
    share_pairs = [(s, data42[s][0] * 100) for s in shards]
    asr42_pairs = [(s, data42[s][1])        for s in shards]
    asr0_pairs  = [(s, data0[s][1])          for s in shards]

    lines = [
        "% AUTO-GENERATED by scripts/make_singleshard_pgf.py",
        "% Sources:",
        f"%   s42: {args.s42}",
        f"%   s0:  {args.s0}",
        "% Do not edit by hand -- rerun the script to update.",
        "",
        "% Series 1: share_s x 100 (blue bars)",
        r"\addplot[fill=blue!40!white, draw=blue!70!black] coordinates {",
        coords_block(share_pairs),
        "};",
        r"\addlegendentry{$\mathrm{share}_s \times 100$}",
        "",
        "% Series 2: single-shard ASR seed-42 (red bars)",
        r"\addplot[fill=red!40!white, draw=red!70!black] coordinates {",
        coords_block(asr42_pairs),
        "};",
        r"\addlegendentry{ASR seed~42}",
        "",
        "% Series 3: single-shard ASR seed-0 (orange bars)",
        r"\addplot[fill=orange!50!white, draw=orange!80!black] coordinates {",
        coords_block(asr0_pairs),
        "};",
        r"\addlegendentry{ASR seed~0}",
    ]

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {args.out}  ({n_shards} shards)")
    print(f"  share x100 : {[f's{s}={v:.2f}' for s, v in share_pairs]}")
    print(f"  ASR s42    : {[f's{s}={v:.2f}' for s, v in asr42_pairs]}")
    print(f"  ASR s0     : {[f's{s}={v:.2f}' for s, v in asr0_pairs]}")


if __name__ == "__main__":
    main()
