"""
make_kcurve_pgf.py -- generate Fig. fig:kcurve coordinate data
(paper/fig_kcurve_data.tex) from the all-subsets JSONs, so no number
in the figure is typed by hand.

Four \addplot coordinate blocks are emitted (no axis environment):
  1. ASR, seed-42, greedy repair-aware path  (red line)
  2. ASR, seed-0,  greedy repair-aware path  (orange line)
  3. CA,  seed-42, greedy repair-aware path  (blue dashed)
  4. CA,  seed-0,  greedy repair-aware path  (teal dashed)

x-axis: k = 0 .. 6  (number of shards rolled back)
  k=0 : empty subset  = repaired model (no rollback)
  k=1..5 : greedy path built by adding shards in descending share_s order
  k=6 : full rollback = all shards  (infected model, same for both seeds)

Greedy order is computed from the 1-shard share_covered values in the s42
JSON (share_covered is geometry of the repair, identical in both JSONs).

Pattern follows make_locality_pgf.py per notes/2026-09-25_hung_supervisor.md.

Usage (run from repo root):
    python scripts/make_kcurve_pgf.py
    python scripts/make_kcurve_pgf.py \\
        --s42 results/raw/all_subsets/finetune_s42_bb_n6.json \\
        --s0  results/raw/all_subsets/finetune_s0_bb_n6.json \\
        --out paper/fig_kcurve_data.tex
"""
import argparse
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_records(path):
    """Load subset records from JSON; handles both {"subsets":[...]} and [...] formats."""
    d = json.load(open(path))
    return d["subsets"] if isinstance(d, dict) else d


def load_index(path):
    """Return dict: frozenset(shards) -> (asr, ca) for every record in the JSON."""
    index = {}
    for r in load_records(path):
        key = frozenset(r["shards"])
        index[key] = (r["asr"], r["ca"])
    return index


def greedy_order(path):
    """
    Return shard indices sorted by share_covered descending (repair-aware order).
    Computed from the 1-shard records in path.
    """
    single = {}
    for r in load_records(path):
        if len(r["shards"]) == 1:
            single[r["shards"][0]] = r["share_covered"]
    return sorted(single, key=lambda s: single[s], reverse=True)


def coords_block(pairs):
    """pairs: list of (x, y); returns indented coordinate lines."""
    return "\n".join(f"    ({x}, {y:.2f})" for x, y in pairs)


def main():
    ap = argparse.ArgumentParser(
        description="Emit fig_kcurve_data.tex from all-subsets JSONs."
    )
    ap.add_argument(
        "--s42",
        default=os.path.join(ROOT, "results/raw/all_subsets/finetune_s42_bb_n6.json"),
        help="Seed-42 all-subsets JSON",
    )
    ap.add_argument(
        "--s0",
        default=os.path.join(ROOT, "results/raw/all_subsets/finetune_s0_bb_n6.json"),
        help="Seed-0 all-subsets JSON",
    )
    ap.add_argument(
        "--out",
        default=os.path.join(ROOT, "paper/fig_kcurve_data.tex"),
        help="Output .tex file (default: paper/fig_kcurve_data.tex)",
    )
    args = ap.parse_args()

    idx42 = load_index(args.s42)
    idx0  = load_index(args.s0)

    # Greedy order from s42 (share_covered is geometry, same in both JSONs)
    order = greedy_order(args.s42)
    n_shards = len(order)  # 6

    # Build greedy path: k=0 (empty) .. k=6 (all shards)
    asr42, ca42, asr0, ca0 = [], [], [], []
    for k in range(n_shards + 1):
        subset = frozenset(order[:k])
        if subset not in idx42:
            raise KeyError(f"k={k} greedy subset {set(subset)} not found in s42 JSON")
        if subset not in idx0:
            raise KeyError(f"k={k} greedy subset {set(subset)} not found in s0 JSON")
        a42, c42 = idx42[subset]
        a0,  c0  = idx0[subset]
        asr42.append((k, a42))
        ca42.append((k, c42))
        asr0.append((k, a0))
        ca0.append((k, c0))

    # Annotate each k with the subset for the comment header
    path_rows = []
    for k in range(n_shards + 1):
        subset = set(order[:k])
        a42, c42 = idx42[frozenset(order[:k])]
        a0,  c0  = idx0[frozenset(order[:k])]
        path_rows.append(
            f"%   k={k}: shards={sorted(subset)}  "
            f"s42 ASR={a42:.2f} CA={c42:.2f}  s0 ASR={a0:.2f} CA={c0:.2f}"
        )

    lines = [
        "% AUTO-GENERATED by scripts/make_kcurve_pgf.py",
        "% Sources:",
        f"%   s42: {args.s42}",
        f"%   s0:  {args.s0}",
        f"% Greedy order (descending share_s): {order}",
        "% Greedy path:",
        *path_rows,
        "% Do not edit by hand -- rerun the script to update.",
        "",
        "% Series 1: ASR seed-42, greedy repair-aware path (red line)",
        r"\addplot[color=red!75!black, mark=*, mark size=1.8pt, thick] coordinates {",
        coords_block(asr42),
        "};",
        r"\addlegendentry{ASR seed~42 (repair-aware)}",
        "",
        "% Series 2: ASR seed-0, greedy repair-aware path (orange line)",
        r"\addplot[color=orange!80!black, mark=square*, mark size=1.8pt, thick] coordinates {",
        coords_block(asr0),
        "};",
        r"\addlegendentry{ASR seed~0 (repair-aware)}",
        "",
        "% Series 3: CA seed-42, greedy repair-aware path (blue dashed)",
        r"\addplot[color=blue!70!black, mark=o, mark size=1.6pt, dashed] coordinates {",
        coords_block(ca42),
        "};",
        r"\addlegendentry{CA seed~42}",
        "",
        "% Series 4: CA seed-0, greedy repair-aware path (teal dashed)",
        r"\addplot[color=teal!80!black, mark=triangle*, mark size=1.6pt, dashed] coordinates {",
        coords_block(ca0),
        "};",
        r"\addlegendentry{CA seed~0}",
    ]

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {args.out}  (k=0..{n_shards})")
    print(f"  Greedy order: {order}")
    for k in range(n_shards + 1):
        a42, c42 = idx42[frozenset(order[:k])]
        a0,  c0  = idx0[frozenset(order[:k])]
        print(f"  k={k}: ASR s42={a42:.2f} CA s42={c42:.2f} | ASR s0={a0:.2f} CA s0={c0:.2f}")


if __name__ == "__main__":
    main()
