#!/usr/bin/env python3
"""Print every number the paper cites, computed from the result JSON files.

    python3 scripts/make_digest.py > results/analysis/2026-09-28_hung_digest_v2.md

The JSON wins over any number typed into the paper or the notes.
"""
import itertools
import json
import os
import statistics as st

from scipy.stats import pearsonr, spearmanr

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RUNS = {"s42": "results/raw/all_subsets/finetune_s42_bb_n6.json",
        "s0": "results/raw/all_subsets/finetune_s0_bb_n6_v2.json"}
NAMES = ["conv1", "layer1", "layer2", "layer3", "layer4", "linear"]
N = 6
FULL = tuple(range(N))


def load(path):
    d = json.load(open(os.path.join(ROOT, path)))
    runs = {tuple(sorted(r["shards"])): r for r in d["subsets"]}
    return runs, d["share_s"], d


def fmt(s):
    return "{" + ",".join(map(str, s)) + "}" if s else "{}"


def main():
    D = {k: load(p) for k, p in RUNS.items()}
    A, shA, _ = D["s42"]
    B, shB, _ = D["s0"]
    P = print
    P("# Results Digest v2, 28 September 2026 (BackdoorBench normalization)\n")
    P("Generated by `scripts/make_digest.py` from " + ", ".join(f"`{p}`" for p in RUNS.values())
      + ". Seed 0 now comes from the v2 file (re-run end to end on its own checkpoint, so its shares, ASR, and CA"
      " belong to one model). This page supersedes the seed-0 columns of `2026-09-26_hung_digest.md`.\n")
    for name, (R, sh, d) in D.items():
        P(f"- **{name}**: repaired checkpoint `{d['repaired_ckpt']}`; full-rollback sanity {d['sanity_full_rollback']}.")
    P("\n## 1. Endpoints\n\n| | s42 ASR | s42 CA | s0 ASR | s0 CA |\n|---|---|---|---|---|")
    P(f"| Infected (k=6) | {A[FULL]['asr']:.2f} | {A[FULL]['ca']:.2f} | {B[FULL]['asr']:.2f} | {B[FULL]['ca']:.2f} |")
    P(f"| Repaired (k=0) | {A[()]['asr']:.2f} | {A[()]['ca']:.2f} | {B[()]['asr']:.2f} | {B[()]['ca']:.2f} |")
    P("\n## 2. Per-shard share and single-shard rollback\n")
    P("| Shard | Layer | s42 share | s0 share | s42 ASR | s42 CA | s0 ASR | s0 CA |\n|---|---|---|---|---|---|---|---|")
    for i in range(N):
        P(f"| {i} | {NAMES[i]} | {100*shA[i]:.2f}% | {100*shB[i]:.2f}% | {A[(i,)]['asr']:.2f} | {A[(i,)]['ca']:.2f} "
          f"| {B[(i,)]['asr']:.2f} | {B[(i,)]['ca']:.2f} |")
    for name, (R, sh, _) in D.items():
        single = [R[(i,)]["asr"] for i in range(N)]
        ca1 = [R[(i,)]["ca"] for i in range(N)]
        lo = min(range(N), key=lambda i: single[i])
        P(f"\n{name}: max single-shard ASR {max(single):.2f} (shard {single.index(max(single))}); "
          f"lowest {min(single):.2f} (shard {lo}); shard 3 alone {single[3]:.2f}; "
          f"single-shard CA {min(ca1):.2f}-{max(ca1):.2f}.")
    P("\n## 3. Repair-aware path (each repair uses its own share order)\n")
    for name, (R, sh, _) in D.items():
        order = sorted(range(N), key=lambda i: -sh[i])
        P(f"**{name}** order {order}\n\n| k | shards | share covered | ASR | CA |\n|---|---|---|---|---|")
        for k in range(N + 1):
            s = tuple(sorted(order[:k]))
            P(f"| {k} | {fmt(s)} | {100*sum(sh[i] for i in s):.2f}% | {R[s]['asr']:.2f} | {R[s]['ca']:.2f} |")
        rep = R[()]["ca"]
        k4 = tuple(sorted(order[:4]))
        P(f"\nk=4 CA gap: {rep - R[k4]['ca']:.2f} below repaired, {R[FULL]['ca'] - R[k4]['ca']:.2f} below infected.\n")
    P("## 4. Architectural path and exact mean over all C(6,k) subsets\n")
    P("| k | s42 arch | s0 arch | s42 mean | s0 mean |\n|---|---|---|---|---|")
    for k in range(1, N):
        ar = tuple(range(k))
        mA = st.mean(A[s]["asr"] for s in itertools.combinations(range(N), k))
        mB = st.mean(B[s]["asr"] for s in itertools.combinations(range(N), k))
        P(f"| {k} | {A[ar]['asr']:.2f} | {B[ar]['asr']:.2f} | {mA:.2f} | {mB:.2f} |")
    P("\n## 5. Best subset per k (exhaustive adversary)\n\n| k | s42 best | ASR | CA | s0 best | ASR | CA |\n|---|---|---|---|---|---|---|")
    for k in range(1, N):
        bA = max(itertools.combinations(range(N), k), key=lambda s: A[s]["asr"])
        bB = max(itertools.combinations(range(N), k), key=lambda s: B[s]["asr"])
        P(f"| {k} | {fmt(bA)} | {A[bA]['asr']:.2f} | {A[bA]['ca']:.2f} | {fmt(bB)} | {B[bB]['asr']:.2f} | {B[bB]['ca']:.2f} |")
    P("\n## 6. Which shards matter\n")
    for name, (R, sh, _) in D.items():
        above = [s for s in R if R[s]["asr"] > 50]
        nec = [NAMES[i] for i in range(N) if all(i in s for s in above)]
        over = [(fmt(s), R[s]["asr"]) for s in R if R[s]["asr"] > R[FULL]["asr"]]
        P(f"- {name}: {len(above)} subsets above 50% ASR; shards in all of them: {nec}; "
          f"subsets above the infected ASR: {over or 'none'}.")
    P("\n## 7. Share versus ASR, and agreement between the two repairs\n")
    for label, subs in (("63 non-empty subsets (k=1..6, the points in Fig. 3)", [s for s in A if s]),
                        ("62 partial subsets (k=1..5)", [s for s in A if 0 < len(s) < N]),
                        ("all 64 subsets", list(A))):
        rA = spearmanr([A[s]["share_covered"] for s in subs], [A[s]["asr"] for s in subs])[0]
        rB = spearmanr([B[s]["share_covered"] for s in subs], [B[s]["asr"] for s in subs])[0]
        agree = sum((A[s]["asr"] > 50) == (B[s]["asr"] > 50) for s in subs)
        r = pearsonr([A[s]["asr"] for s in subs], [B[s]["asr"] for s in subs])[0]
        P(f"- {label}: Spearman s42 {rA:.3f}, s0 {rB:.3f}; agree on >50% in {agree} of {len(subs)}; "
          f"Pearson ASR s42 vs s0 {r:.3f}.")
    dis = [(fmt(s), A[s]["asr"], B[s]["asr"]) for s in A if s and (A[s]["asr"] > 50) != (B[s]["asr"] > 50)]
    P(f"- Disagreements (s42 ASR, s0 ASR): {dis}")
    P("\n## 8. Hybrid clean accuracy, k=1..5\n")
    for name, (R, sh, _) in D.items():
        cas = [R[s]["ca"] for s in R if 0 < len(s) < N]
        P(f"- {name}: {min(cas):.2f}-{max(cas):.2f}")


if __name__ == "__main__":
    main()
