"""
make_locality_pgf.py -- generate the data for Fig. "repair share vs recovered ASR"
(paper/fig_locality_data.tex) straight from results/raw, so no number in the
figure is typed by hand.

Each point is one rolled-back shard subset: x = repair share covered (%),
y = ASR (%). Subsets containing both layer2 (shard 2) and layer4 (shard 4)
are drawn as a separate series.

Sources, in priority order:
  1. --all-subsets JSON(s) from scripts/eval_all_subsets.py   (preferred)
  2. legacy pooled data: results/raw/kshard*/kshard_curve_n6.json +
     results/raw/substitution/n6/shard*.json + results/raw/share/share_n6.json

Usage:
    python scripts/make_locality_pgf.py --legacy                       # today
    python scripts/make_locality_pgf.py \
        --all-subsets results/raw/all_subsets/finetune_s42_n6.json \
        --anp results/raw/all_subsets/anp_v2_n6.json                  # after re-runs
"""
import argparse
import glob
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def legacy_points():
    share = {r["shard_idx"]: r["share_s"] for r in
             json.load(open(os.path.join(ROOT, "results/raw/share/share_n6.json")))["shards"]}
    pts = {}
    for f in glob.glob(os.path.join(ROOT, "results/raw/kshard*/kshard_curve_n6.json")):
        if "anp" in f:
            continue
        for v in json.load(open(f)).values():
            for name, r in v.get("strategies", {}).items():
                if name == "random":
                    for d, a, c in zip(r["draws"], r["asr_per_draw"], r["ca_per_draw"]):
                        pts[tuple(sorted(d))] = (a, c)
                else:
                    pts[tuple(sorted(r["shards"]))] = (r["asr"], r["ca"])
    for f in glob.glob(os.path.join(ROOT, "results/raw/substitution/n6/shard*.json")):
        j = json.load(open(f))
        pts[(j["shard_idx"],)] = (j["asr"], j["ca"])
    return [(sub, 100 * sum(share[s] for s in sub), a, c) for sub, (a, c) in pts.items() if sub]


def subset_points(path):
    d = json.load(open(path))
    return [(tuple(r["shards"]), 100 * r["share_covered"], r["asr"], r["ca"])
            for r in d["subsets"] if r["shards"]]


def coords(points):
    return "\n".join(f"    ({x:.2f}, {y:.2f})  % {list(sub)} CA={ca:.2f}"
                     for sub, x, y, ca in sorted(points, key=lambda p: p[1]))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--legacy", action="store_true")
    ap.add_argument("--all-subsets", default=None, help="fine-tune all-subsets JSON")
    ap.add_argument("--anp", default=None, help="ANP all-subsets JSON (optional)")
    ap.add_argument("--out", default=os.path.join(ROOT, "paper/fig_locality_data.tex"))
    args = ap.parse_args()

    pts = subset_points(args.all_subsets) if args.all_subsets else legacy_points()
    both = [p for p in pts if 2 in p[0] and 4 in p[0]]
    rest = [p for p in pts if not (2 in p[0] and 4 in p[0])]
    src = args.all_subsets or "legacy pooled kshard + substitution/n6 JSONs"
    lines = [
        f"% AUTO-GENERATED by scripts/make_locality_pgf.py from {src}. Do not edit by hand.",
        f"% {len(pts)} subsets; {len(both)} contain shards 2 and 4.",
        f"% min ASR with {{2,4}}: {min(p[2] for p in both):.2f}; "
        f"max ASR without: {max(p[2] for p in rest):.2f}",
        "\\addplot[only marks, mark=o, mark size=2pt, color=blue!70!black] coordinates {",
        coords(rest), "};",
        "\\addlegendentry{Fine-tune, without \\{2,4\\}}",
        "\\addplot[only marks, mark=*, mark size=2pt, color=red!75!black] coordinates {",
        coords(both), "};",
        "\\addlegendentry{Fine-tune, with \\{2,4\\}}",
    ]
    if args.anp:
        ap_pts = subset_points(args.anp)
        lines += ["\\addplot[only marks, mark=triangle*, mark size=2.2pt, color=orange!85!black] coordinates {",
                  coords(ap_pts), "};", "\\addlegendentry{ANP}"]
    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {args.out}: {len(pts)} fine-tune points ({len(both)} with {{2,4}})"
          + (f", {len(subset_points(args.anp))} ANP points" if args.anp else ""))
    print(lines[1]); print(lines[2])


if __name__ == "__main__":
    main()
